server:
  port: 1027
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${eureka.instance.hostname}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:1025/eureka/,http://localhost:1026/eureka/,http://localhost:1027/eureka/
  server:
    enable-self-preservation: false